version: "3.3"

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/marufs/media/sonarr:/config
      - /home/marufs/media/downloads:/downloads
      - /home/marufs/media/tv:/tv
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/marufs/media/radarr:/config
      - /home/marufs/media/downloads:/downloads
      - /home/marufs/media/movies:/movies
    ports:
      - 7878:7878
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/marufs/media/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - QBT_USERNAME=admin
      - QBT_PASSWORD=mypassword
    volumes:
      - /home/marufs/media/qbittorrent:/config
      - /home/marufs/media/downloads:/downloads
    ports:
      - 8080:8080    # Web UI
      - 6881:6881    # TCP torrent port
      - 6881:6881/udp # UDP torrent port
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/marufs/media/jellyfin:/config
      - /home/marufs/media/tv:/data/tv
      - /home/marufs/media/movies:/data/movies
      - /home/marufs/media/downloads:/downloads
    ports:
      - 8096:8096     # Web UI (HTTP)
      # - 8920:8920   # Optional: HTTPS if enabled
    restart: unless-stopped

volumes:
  portainer_data:
  sonarr:
  radarr:
  prowlarr:
  qbittorrent:
  jellyfin:
